# Site settings
name: OptiKey
title: ""
email: ""
description: "OptiKey is free and open source software, designed to be used with a low cost eye-tracking device to bring keyboard control, mouse control and speech to people with motor and speech limitations."
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

stylesheet: css/style.css

scripts:
  - /assets/js/jquery-2.1.0.min.js
  - /assets/js/bootstrap.min.js


navigation:
- text: Home
  url: /en/
- text: Get Started
  url: /en/get-started/
- text: Guides
  url: /en/guides/
- text: Download
  url: /en/download/
- text: About
  url: /en/about/