# Site settings
name: OptiKey
title: ""
email: ""
description: "OptiKey is free and open source software, designed to be used with a low cost eye-tracking device to bring keyboard control, mouse control and speech to people with motor and speech limitations."
baseurl: ""
url: ""

baseurl: "/optikey"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

stylesheet: /optikey/assets/css/style.css

scripts:
  - /optikey/assets/js/jquery-2.1.0.min.js
  - /optikey/assets/js/bootstrap.min.js


navigation:
  en:
    - text: Home
      url: /optikey/en/
    - text: Get Started
      url: /optikey/en/get-started/
    - text: Guides
      url: /optikey/en/guides/
    - text: Download
      url: /optikey/en/download/
    - text: About
      url: /optikey/en/about/